### ISSUE TITLE
Ambiguity with `cpu` and `gpu`

### ISSUE THREAD

**Issue by mjyshin** [rmsrosa/ChainPlot.jl#5]
1. This is a nice package. Will you be registering it with the package manager soon?
2. Going with the trend "Plots" and "StatsPlots", adding an "s" at the end ("ChainPlots") might be nice.
3. There is some issue using your package with CUDA and Flux:
```julia
using CUDA, Flux, ChainPlot
arr = [1,2,3] |> cpu
```
leads to:
```
MethodError: adapt_storage(::Flux.FluxCPUAdaptor, ::Vector{Int64}) is ambiguous. Candidates:
  adapt_storage(NeuronState, xs::AbstractArray{<:Number}) in ChainPlot.NeuronNumbers at C:\Users\matth\.julia\packages\ChainPlot\XVMxo\src\NeuronNumbers.jl:137
  adapt_storage(to::Flux.FluxCPUAdaptor, x::AbstractArray) in Flux at C:\Users\matth\.julia\packages\Flux\qAdFM\src\functor.jl:106
Possible fix, define
  adapt_storage(::Flux.FluxCPUAdaptor, ::AbstractArray{<:Number})
```
The same issue with GPU, e.g., `[1,2,3] |> gpu`...

**Comment by rmsrosa** [comment]
1. Thanks! Yeah, this should be registered at some point. I want at least to improve the visualization for multidimensional layers; it is kind of ugly right now, among other things. The plan was to PR to Flux.jl, but I think it would be better as a separate package, either here or in FluxML.
2. Yeah, "ChainPlots" sounds good. I think I thought about this before but don't remember why I chose the singular form. I will change it.
3. Hmm, yeah, I never tested CUDA because I don't have a GPU to play with, but indeed I can see the error in `[1,2,3] |> cpu`. It should be fixed, now.  I had not typed properly the first argument to `adapt_storage`. Have a go and let me know, please.

**Comment by rmsrosa** [comment]
fixed in commit a8d77eeb86c8f2e321cdf8d5fb2737984f1ac1f4

**Comment by mjyshin** [comment]
Thanks for the fix, it works great! And if you have the patience and won't get too mad when Google cuts off your GPU access randomly and indefinitely, you could always try the free version of Google Colab for a GPU; it's a cool concept but personally a bit too annoying currently. And I really hope you keep working on this, I think it'll be a great instructional tool to be able to quickly visualize networks ([here](https://github.com/mjyshin/math-tutorials/blob/main/deep_learning/2_least_squares.ipynb)'s a simple example where I recently used it).

**Comment by rmsrosa** [comment]
Very nice example! Thanks for sharing it.

As for the Google Colab with GPU, do you have/know of a minimum setup to use it with Julia?

**Comment by mjyshin** [comment]
I am not sure of any minimum requirements other than having a Google (Gmail) account. [Here](https://colab.research.google.com/drive/1at8ExRcQbYuS3rgcKal9h7zDTgR6v5Gw?usp=sharing)'s the same notebook, but using Julia in Google Colab (it's a bit finicky right now, but I'm sure they'll incorporate Julia much more easily in they future like they do Python currently). I just copied and pasted the first few blocks from the template [here](https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb) and changed them to include whatever packages I wanted. Hope this helps!

**Comment by rmsrosa** [comment]
Excellent, this template is exactly what I was looking for. Both the template and the notebook ran fine. Thanks a lot!
